//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGrade.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-64")]
        public double setCam_pitch {
            get {
                return ((double)(this["setCam_pitch"]));
            }
            set {
                this["setCam_pitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM GPS...")]
        public string setPort_portNameGPS {
            get {
                return ((string)(this["setPort_portNameGPS"]));
            }
            set {
                this["setPort_portNameGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public int setPort_baudRate {
            get {
                return ((int)(this["setPort_baudRate"]));
            }
            set {
                this["setPort_baudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30")]
        public global::System.Drawing.Point setWindow_Location {
            get {
                return ((global::System.Drawing.Point)(this["setWindow_Location"]));
            }
            set {
                this["setWindow_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1016, 839")]
        public global::System.Drawing.Size setWindow_Size {
            get {
                return ((global::System.Drawing.Size)(this["setWindow_Size"]));
            }
            set {
                this["setWindow_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Maximized {
            get {
                return ((bool)(this["setWindow_Maximized"]));
            }
            set {
                this["setWindow_Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Minimized {
            get {
                return ((bool)(this["setWindow_Minimized"]));
            }
            set {
                this["setWindow_Minimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM Section...")]
        public string setPort_portNameRateRelay {
            get {
                return ((string)(this["setPort_portNameRateRelay"]));
            }
            set {
                this["setPort_portNameRateRelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasRateRelayConnected {
            get {
                return ((bool)(this["setPort_wasRateRelayConnected"]));
            }
            set {
                this["setPort_wasRateRelayConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isMetric {
            get {
                return ((bool)(this["setMenu_isMetric"]));
            }
            set {
                this["setMenu_isMetric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isGridOn {
            get {
                return ((bool)(this["setMenu_isGridOn"]));
            }
            set {
                this["setMenu_isGridOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isLightbarOn {
            get {
                return ((bool)(this["setMenu_isLightbarOn"]));
            }
            set {
                this["setMenu_isLightbarOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setF_CurrentDir {
            get {
                return ((string)(this["setF_CurrentDir"]));
            }
            set {
                this["setF_CurrentDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public byte setF_FieldColorR {
            get {
                return ((byte)(this["setF_FieldColorR"]));
            }
            set {
                this["setF_FieldColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public byte setF_FieldColorG {
            get {
                return ((byte)(this["setF_FieldColorG"]));
            }
            set {
                this["setF_FieldColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public byte setF_FieldColorB {
            get {
                return ((byte)(this["setF_FieldColorB"]));
            }
            set {
                this["setF_FieldColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte setF_SectionColorR {
            get {
                return ((byte)(this["setF_SectionColorR"]));
            }
            set {
                this["setF_SectionColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public byte setF_SectionColorG {
            get {
                return ((byte)(this["setF_SectionColorG"]));
            }
            set {
                this["setF_SectionColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public byte setF_SectionColorB {
            get {
                return ((byte)(this["setF_SectionColorB"]));
            }
            set {
                this["setF_SectionColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setF_IsWorkSwitchActiveLow {
            get {
                return ((bool)(this["setF_IsWorkSwitchActiveLow"]));
            }
            set {
                this["setF_IsWorkSwitchActiveLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setF_IsWorkSwitchEnabled {
            get {
                return ((bool)(this["setF_IsWorkSwitchEnabled"]));
            }
            set {
                this["setF_IsWorkSwitchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM AS")]
        public string setPort_portNameAutoSteer {
            get {
                return ((string)(this["setPort_portNameAutoSteer"]));
            }
            set {
                this["setPort_portNameAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasAutoSteerConnected {
            get {
                return ((bool)(this["setPort_wasAutoSteerConnected"]));
            }
            set {
                this["setPort_wasAutoSteerConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setIMU_pitchZero {
            get {
                return ((double)(this["setIMU_pitchZero"]));
            }
            set {
                this["setIMU_pitchZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setIMU_rollZero {
            get {
                return ((double)(this["setIMU_rollZero"]));
            }
            set {
                this["setIMU_rollZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isLogNMEA {
            get {
                return ((bool)(this["setMenu_isLogNMEA"]));
            }
            set {
                this["setMenu_isLogNMEA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte setAS_Ko {
            get {
                return ((byte)(this["setAS_Ko"]));
            }
            set {
                this["setAS_Ko"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte setAS_Kp {
            get {
                return ((byte)(this["setAS_Kp"]));
            }
            set {
                this["setAS_Kp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setAS_Ki {
            get {
                return ((byte)(this["setAS_Ki"]));
            }
            set {
                this["setAS_Ki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte setAS_Kd {
            get {
                return ((byte)(this["setAS_Kd"]));
            }
            set {
                this["setAS_Kd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public byte setAS_steerAngleOffset {
            get {
                return ((byte)(this["setAS_steerAngleOffset"]));
            }
            set {
                this["setAS_steerAngleOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setF_UserTripAlarm {
            get {
                return ((double)(this["setF_UserTripAlarm"]));
            }
            set {
                this["setF_UserTripAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setF_UserTotalArea {
            get {
                return ((double)(this["setF_UserTotalArea"]));
            }
            set {
                this["setF_UserTotalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte setAS_minSteerPWM {
            get {
                return ((byte)(this["setAS_minSteerPWM"]));
            }
            set {
                this["setAS_minSteerPWM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte setAS_maxIntegral {
            get {
                return ((byte)(this["setAS_maxIntegral"]));
            }
            set {
                this["setAS_maxIntegral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte setAS_countsPerDegree {
            get {
                return ((byte)(this["setAS_countsPerDegree"]));
            }
            set {
                this["setAS_countsPerDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isPureOn {
            get {
                return ((bool)(this["setMenu_isPureOn"]));
            }
            set {
                this["setMenu_isPureOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int setIP_thisPort {
            get {
                return ((int)(this["setIP_thisPort"]));
            }
            set {
                this["setIP_thisPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.5.255")]
        public string setIP_autoSteerIP {
            get {
                return ((string)(this["setIP_autoSteerIP"]));
            }
            set {
                this["setIP_autoSteerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setIP_autoSteerPort {
            get {
                return ((int)(this["setIP_autoSteerPort"]));
            }
            set {
                this["setIP_autoSteerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.5.255")]
        public string setIP_rateRelayIP {
            get {
                return ((string)(this["setIP_rateRelayIP"]));
            }
            set {
                this["setIP_rateRelayIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8888")]
        public int setIP_rateRelayPort {
            get {
                return ((int)(this["setIP_rateRelayPort"]));
            }
            set {
                this["setIP_rateRelayPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isSimulatorOn {
            get {
                return ((bool)(this["setMenu_isSimulatorOn"]));
            }
            set {
                this["setMenu_isSimulatorOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53.436026")]
        public double setSim_lastLat {
            get {
                return ((double)(this["setSim_lastLat"]));
            }
            set {
                this["setSim_lastLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-111.160047")]
        public double setSim_lastLong {
            get {
                return ((double)(this["setSim_lastLong"]));
            }
            set {
                this["setSim_lastLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isSkyOn {
            get {
                return ((bool)(this["setMenu_isSkyOn"]));
            }
            set {
                this["setMenu_isSkyOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string set_culture {
            get {
                return ((string)(this["set_culture"]));
            }
            set {
                this["set_culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string setF_workingDirectory {
            get {
                return ((string)(this["setF_workingDirectory"]));
            }
            set {
                this["setF_workingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double setF_minFixStep {
            get {
                return ((double)(this["setF_minFixStep"]));
            }
            set {
                this["setF_minFixStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Set_isAvgPt {
            get {
                return ((bool)(this["Set_isAvgPt"]));
            }
            set {
                this["Set_isAvgPt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Set_noAvgDist {
            get {
                return ((double)(this["Set_noAvgDist"]));
            }
            set {
                this["Set_noAvgDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Set_levelDistFactor {
            get {
                return ((double)(this["Set_levelDistFactor"]));
            }
            set {
                this["Set_levelDistFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public byte setF_FillColorR {
            get {
                return ((byte)(this["setF_FillColorR"]));
            }
            set {
                this["setF_FillColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("133")]
        public byte setF_FillColorG {
            get {
                return ((byte)(this["setF_FillColorG"]));
            }
            set {
                this["setF_FillColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public byte setF_FillColorB {
            get {
                return ((byte)(this["setF_FillColorB"]));
            }
            set {
                this["setF_FillColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191")]
        public byte setF_CenterColorR {
            get {
                return ((byte)(this["setF_CenterColorR"]));
            }
            set {
                this["setF_CenterColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191")]
        public byte setF_CenterColorG {
            get {
                return ((byte)(this["setF_CenterColorG"]));
            }
            set {
                this["setF_CenterColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191")]
        public byte setF_CenterColorB {
            get {
                return ((byte)(this["setF_CenterColorB"]));
            }
            set {
                this["setF_CenterColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191")]
        public byte setF_CutColorR {
            get {
                return ((byte)(this["setF_CutColorR"]));
            }
            set {
                this["setF_CutColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setF_CutColorG {
            get {
                return ((byte)(this["setF_CutColorG"]));
            }
            set {
                this["setF_CutColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setF_CutColorB {
            get {
                return ((byte)(this["setF_CutColorB"]));
            }
            set {
                this["setF_CutColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("69.75.31.235")]
        public string setNTRIP_casterIP {
            get {
                return ((string)(this["setNTRIP_casterIP"]));
            }
            set {
                this["setNTRIP_casterIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2101")]
        public int setNTRIP_casterPort {
            get {
                return ((int)(this["setNTRIP_casterPort"]));
            }
            set {
                this["setNTRIP_casterPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AZU1")]
        public string setNTRIP_mount {
            get {
                return ((string)(this["setNTRIP_mount"]));
            }
            set {
                this["setNTRIP_mount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setNTRIP_userName {
            get {
                return ((string)(this["setNTRIP_userName"]));
            }
            set {
                this["setNTRIP_userName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setNTRIP_userPassword {
            get {
                return ((string)(this["setNTRIP_userPassword"]));
            }
            set {
                this["setNTRIP_userPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isOn {
            get {
                return ((bool)(this["setNTRIP_isOn"]));
            }
            set {
                this["setNTRIP_isOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int setNTRIP_sendGGAInterval {
            get {
                return ((int)(this["setNTRIP_sendGGAInterval"]));
            }
            set {
                this["setNTRIP_sendGGAInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2233")]
        public int setNTRIP_sendToUDPPort {
            get {
                return ((int)(this["setNTRIP_sendToUDPPort"]));
            }
            set {
                this["setNTRIP_sendToUDPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53")]
        public double setNTRIP_manualLat {
            get {
                return ((double)(this["setNTRIP_manualLat"]));
            }
            set {
                this["setNTRIP_manualLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-111")]
        public double setNTRIP_manualLon {
            get {
                return ((double)(this["setNTRIP_manualLon"]));
            }
            set {
                this["setNTRIP_manualLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.rtk2go.com")]
        public string setNTRIP_casterURL {
            get {
                return ((string)(this["setNTRIP_casterURL"]));
            }
            set {
                this["setNTRIP_casterURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isGGAManual {
            get {
                return ((bool)(this["setNTRIP_isGGAManual"]));
            }
            set {
                this["setNTRIP_isGGAManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isHTTP10 {
            get {
                return ((bool)(this["setNTRIP_isHTTP10"]));
            }
            set {
                this["setNTRIP_isHTTP10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isTCP {
            get {
                return ((bool)(this["setNTRIP_isTCP"]));
            }
            set {
                this["setNTRIP_isTCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string setF_culture {
            get {
                return ((string)(this["setF_culture"]));
            }
            set {
                this["setF_culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDisplay_isKeyboardOn {
            get {
                return ((bool)(this["setDisplay_isKeyboardOn"]));
            }
            set {
                this["setDisplay_isKeyboardOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setF_FillMidColorR {
            get {
                return ((byte)(this["setF_FillMidColorR"]));
            }
            set {
                this["setF_FillMidColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191")]
        public byte setF_FillMidColorG {
            get {
                return ((byte)(this["setF_FillMidColorG"]));
            }
            set {
                this["setF_FillMidColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte setF_FillMidColorB {
            get {
                return ((byte)(this["setF_FillMidColorB"]));
            }
            set {
                this["setF_FillMidColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setF_FillMinColorR {
            get {
                return ((byte)(this["setF_FillMinColorR"]));
            }
            set {
                this["setF_FillMinColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte setF_FillMinColorG {
            get {
                return ((byte)(this["setF_FillMinColorG"]));
            }
            set {
                this["setF_FillMinColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setF_FillMinColorB {
            get {
                return ((byte)(this["setF_FillMinColorB"]));
            }
            set {
                this["setF_FillMinColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte setF_CutMinColorR {
            get {
                return ((byte)(this["setF_CutMinColorR"]));
            }
            set {
                this["setF_CutMinColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte setF_CutMinColorG {
            get {
                return ((byte)(this["setF_CutMinColorG"]));
            }
            set {
                this["setF_CutMinColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setF_CutMinColorB {
            get {
                return ((byte)(this["setF_CutMinColorB"]));
            }
            set {
                this["setF_CutMinColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte setF_CutMidColorR {
            get {
                return ((byte)(this["setF_CutMidColorR"]));
            }
            set {
                this["setF_CutMidColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public byte setF_CutMidColorG {
            get {
                return ((byte)(this["setF_CutMidColorG"]));
            }
            set {
                this["setF_CutMidColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setF_CutMidColorB {
            get {
                return ((byte)(this["setF_CutMidColorB"]));
            }
            set {
                this["setF_CutMidColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isGradual {
            get {
                return ((bool)(this["setMenu_isGradual"]));
            }
            set {
                this["setMenu_isGradual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isGradualMulticolor {
            get {
                return ((bool)(this["setMenu_isGradualMulticolor"]));
            }
            set {
                this["setMenu_isGradualMulticolor"] = value;
            }
        }
    }
}
