//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGrade.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Vehicle : global::System.Configuration.ApplicationSettingsBase {
        
        private static Vehicle defaultInstance = ((Vehicle)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Vehicle())));
        
        public static Vehicle Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_antennaHeight {
            get {
                return ((double)(this["setVehicle_antennaHeight"]));
            }
            set {
                this["setVehicle_antennaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double setVehicle_wheelbase {
            get {
                return ((double)(this["setVehicle_wheelbase"]));
            }
            set {
                this["setVehicle_wheelbase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default - ")]
        public string setVehicle_Name {
            get {
                return ((string)(this["setVehicle_Name"]));
            }
            set {
                this["setVehicle_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_goalPointLookAhead {
            get {
                return ((double)(this["setVehicle_goalPointLookAhead"]));
            }
            set {
                this["setVehicle_goalPointLookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_maxAngularVelocity {
            get {
                return ((double)(this["setVehicle_maxAngularVelocity"]));
            }
            set {
                this["setVehicle_maxAngularVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double setVehicle_maxSteerAngle {
            get {
                return ((double)(this["setVehicle_maxSteerAngle"]));
            }
            set {
                this["setVehicle_maxSteerAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double setVehicle_toolWidth {
            get {
                return ((double)(this["setVehicle_toolWidth"]));
            }
            set {
                this["setVehicle_toolWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.001")]
        public double setVehicle_minSlope {
            get {
                return ((double)(this["setVehicle_minSlope"]));
            }
            set {
                this["setVehicle_minSlope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte setVehicle_pwmGainUp {
            get {
                return ((byte)(this["setVehicle_pwmGainUp"]));
            }
            set {
                this["setVehicle_pwmGainUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte setVehicle_pwmGainDown {
            get {
                return ((byte)(this["setVehicle_pwmGainDown"]));
            }
            set {
                this["setVehicle_pwmGainDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte setVehicle_pwmMinUp {
            get {
                return ((byte)(this["setVehicle_pwmMinUp"]));
            }
            set {
                this["setVehicle_pwmMinUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte setVehicle_pwmMinDown {
            get {
                return ((byte)(this["setVehicle_pwmMinDown"]));
            }
            set {
                this["setVehicle_pwmMinDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public byte setVehicle_pwmMaxUp {
            get {
                return ((byte)(this["setVehicle_pwmMaxUp"]));
            }
            set {
                this["setVehicle_pwmMaxUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public byte setVehicle_pwmMaxDown {
            get {
                return ((byte)(this["setVehicle_pwmMaxDown"]));
            }
            set {
                this["setVehicle_pwmMaxDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte setVehicle_integralMultiplier {
            get {
                return ((byte)(this["setVehicle_integralMultiplier"]));
            }
            set {
                this["setVehicle_integralMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte setVehicle_deadband {
            get {
                return ((byte)(this["setVehicle_deadband"]));
            }
            set {
                this["setVehicle_deadband"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setVehicle_ViewDistUnderGnd {
            get {
                return ((double)(this["setVehicle_ViewDistUnderGnd"]));
            }
            set {
                this["setVehicle_ViewDistUnderGnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setVehicle_ViewDistAboveGnd {
            get {
                return ((double)(this["setVehicle_ViewDistAboveGnd"]));
            }
            set {
                this["setVehicle_ViewDistAboveGnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double setVehicle_GradeDistFromLine {
            get {
                return ((double)(this["setVehicle_GradeDistFromLine"]));
            }
            set {
                this["setVehicle_GradeDistFromLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setVehicle_MaxCuttingDepth {
            get {
                return ((double)(this["setVehicle_MaxCuttingDepth"]));
            }
            set {
                this["setVehicle_MaxCuttingDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setVehicle_bladeOffset {
            get {
                return ((double)(this["setVehicle_bladeOffset"]));
            }
            set {
                this["setVehicle_bladeOffset"] = value;
            }
        }
    }
}
